/**
 * Regenerates docs/generated/ from the API source.
 *
 * Run with: npx tsx scripts/generate-docs.ts   (or: npm run docs:generate)
 *
 * Schema is read through Drizzle's own table metadata rather than by parsing
 * source text, so column types and foreign keys are whatever Drizzle actually
 * builds. Routes are parsed statically — importing them would pull in the DB
 * client, which requires DATABASE_URL and has no business running here.
 */

import fs from "node:fs";
import path from "node:path";
import { getTableName, is } from "drizzle-orm";
import { PgTable, getTableConfig } from "drizzle-orm/pg-core";

const REPO_ROOT = path.resolve(__dirname, "..");

// If the API moves, these are the only paths that need updating.
const SCHEMA_FILE = path.join(REPO_ROOT, "apps/api/src/db/schema.ts");
const ROUTES_DIR = path.join(REPO_ROOT, "apps/api/src/routes");
const API_ENTRY = path.join(REPO_ROOT, "apps/api/src/index.ts");
const OUT_DIR = path.join(REPO_ROOT, "docs/generated");

const HTTP_METHODS = ["get", "post", "put", "patch", "delete", "all"] as const;

function relativeToRoot(absolute: string) {
  return path.relative(REPO_ROOT, absolute);
}

function header(title: string, sources: string[]) {
  return [
    `<!-- Generated by scripts/generate-docs.ts — do not edit by hand. -->`,
    `<!-- Run \`npm run docs:generate\` to refresh. -->`,
    ``,
    `# ${title}`,
    ``,
    `Generated from ${sources.map((s) => `\`${s}\``).join(", ")}.`,
    ``,
  ].join("\n");
}

/** Mermaid attribute types can't contain spaces. */
function mermaidType(sqlType: string) {
  return sqlType
    .replace(/ with time zone/g, "tz")
    .replace(/ without time zone/g, "")
    .replace(/\s+/g, "_");
}

// ---------------------------------------------------------------- schema ---

type ForeignKeyInfo = {
  column: string;
  targetTable: string;
  targetColumn: string;
  onDelete?: string;
};

async function generateSchemaDoc(): Promise<string | null> {
  if (!fs.existsSync(SCHEMA_FILE)) {
    console.warn(`! Skipping schema: expected Drizzle schema at ${relativeToRoot(SCHEMA_FILE)}`);
    return null;
  }

  const schemaModule: Record<string, unknown> = await import(SCHEMA_FILE);
  const tables = Object.values(schemaModule).filter((value): value is PgTable => is(value, PgTable));

  if (tables.length === 0) {
    console.warn(`! No pgTable exports found in ${relativeToRoot(SCHEMA_FILE)}`);
    return null;
  }

  const entities: string[] = [];
  const relationships: string[] = [];
  const tableSections: string[] = [];

  for (const table of tables) {
    const config = getTableConfig(table);
    const tableName = getTableName(table);

    const foreignKeys: ForeignKeyInfo[] = config.foreignKeys.map((fk) => {
      const ref = fk.reference();
      return {
        column: ref.columns[0]?.name ?? "?",
        targetTable: getTableName(ref.foreignTable),
        targetColumn: ref.foreignColumns[0]?.name ?? "?",
        onDelete: fk.onDelete,
      };
    });
    const fkByColumn = new Map(foreignKeys.map((fk) => [fk.column, fk]));

    // Mermaid entity block
    const attributes = config.columns.map((column) => {
      const keys: string[] = [];
      if (column.primary) keys.push("PK");
      if (fkByColumn.has(column.name)) keys.push("FK");
      if (column.isUnique) keys.push("UK");

      const notes: string[] = [];
      if (!column.notNull) notes.push("nullable");
      if (column.hasDefault) notes.push("has default");

      const parts = [mermaidType(column.getSQLType()), column.name];
      if (keys.length) parts.push(keys.join(","));
      if (notes.length) parts.push(`"${notes.join(", ")}"`);
      return `        ${parts.join(" ")}`;
    });

    entities.push(`    ${tableName} {\n${attributes.join("\n")}\n    }`);

    for (const fk of foreignKeys) {
      // A nullable FK means the child row may exist without a parent.
      const column = config.columns.find((c) => c.name === fk.column);
      const parentCardinality = column?.notNull ? "||" : "|o";
      const label = fk.onDelete ? `${fk.column} (${fk.onDelete})` : fk.column;
      relationships.push(`    ${fk.targetTable} ${parentCardinality}--o{ ${tableName} : "${label}"`);
    }

    // Human-readable table
    const rows = config.columns.map((column) => {
      const fk = fkByColumn.get(column.name);
      const constraints: string[] = [];
      if (column.primary) constraints.push("primary key");
      if (column.isUnique) constraints.push("unique");
      if (column.notNull) constraints.push("not null");
      if (column.hasDefault) constraints.push("default");
      if (fk) {
        constraints.push(
          `→ ${fk.targetTable}.${fk.targetColumn}${fk.onDelete ? ` (on delete ${fk.onDelete})` : ""}`,
        );
      }
      return `| \`${column.name}\` | \`${column.getSQLType()}\` | ${constraints.join(", ") || "—"} |`;
    });

    tableSections.push(
      [
        `### \`${tableName}\``,
        ``,
        `| Column | Type | Constraints |`,
        `| --- | --- | --- |`,
        ...rows,
        ``,
      ].join("\n"),
    );
  }

  return [
    header("Data model", [relativeToRoot(SCHEMA_FILE)]),
    "```mermaid",
    "erDiagram",
    ...relationships,
    ...entities,
    "```",
    "",
    "## Tables",
    "",
    ...tableSections,
  ].join("\n");
}

// ---------------------------------------------------------------- routes ---

type RouteInfo = {
  method: string;
  fullPath: string;
  file: string;
  description?: string;
};

/** Contiguous `//` comment lines directly above a route definition. */
function precedingComment(lines: string[], index: number) {
  const collected: string[] = [];
  for (let i = index - 1; i >= 0; i--) {
    const line = lines[i].trim();
    if (line.startsWith("//")) {
      collected.unshift(line.replace(/^\/\/\s?/, "").trim());
      continue;
    }
    break;
  }
  return collected.length ? collected.join(" ") : undefined;
}

function joinPath(prefix: string, routePath: string) {
  if (routePath === "/" || routePath === "") return prefix || "/";
  return `${prefix}${routePath}`;
}

function generateRoutesDoc(): string | null {
  if (!fs.existsSync(ROUTES_DIR)) {
    console.warn(`! Skipping routes: expected Express routers in ${relativeToRoot(ROUTES_DIR)}`);
    return null;
  }

  // Router variable name -> mount prefix, e.g. tagsRouter -> /tags
  const mountPrefixes = new Map<string, string>();
  const directRoutes: RouteInfo[] = [];

  if (fs.existsSync(API_ENTRY)) {
    const entrySource = fs.readFileSync(API_ENTRY, "utf8");
    const entryLines = entrySource.split("\n");

    const mountRe = /app\.use\(\s*["'`]([^"'`]+)["'`]\s*,\s*(\w+)\s*\)/g;
    for (const match of entrySource.matchAll(mountRe)) {
      mountPrefixes.set(match[2], match[1]);
    }

    const directRe = new RegExp(`app\\.(${HTTP_METHODS.join("|")})\\(\\s*["'\`]([^"'\`]+)["'\`]`);
    entryLines.forEach((line, index) => {
      const match = line.match(directRe);
      if (!match) return;
      directRoutes.push({
        method: match[1].toUpperCase(),
        fullPath: match[2],
        file: relativeToRoot(API_ENTRY),
        description: precedingComment(entryLines, index),
      });
    });
  } else {
    console.warn(`! No API entry at ${relativeToRoot(API_ENTRY)} — route prefixes may be missing`);
  }

  const routerRe = /export const (\w+)\s*=\s*Router\(\)/;
  const routeRe = new RegExp(`^\\s*(\\w+)\\.(${HTTP_METHODS.join("|")})\\(\\s*["'\`]([^"'\`]*)["'\`]`);

  const groups: { prefix: string; file: string; routes: RouteInfo[] }[] = [];

  const files = fs
    .readdirSync(ROUTES_DIR)
    .filter((file) => file.endsWith(".ts"))
    .sort();

  for (const file of files) {
    const absolute = path.join(ROUTES_DIR, file);
    const source = fs.readFileSync(absolute, "utf8");
    const lines = source.split("\n");

    const routerName = source.match(routerRe)?.[1];
    const prefix = routerName ? (mountPrefixes.get(routerName) ?? "") : "";
    if (routerName && !mountPrefixes.has(routerName)) {
      console.warn(`! ${routerName} (${file}) is not mounted in ${relativeToRoot(API_ENTRY)}`);
    }

    const routes: RouteInfo[] = [];
    lines.forEach((line, index) => {
      const match = line.match(routeRe);
      if (!match) return;
      const [, variable, method, routePath] = match;
      if (routerName && variable !== routerName) return;
      routes.push({
        method: method.toUpperCase(),
        fullPath: joinPath(prefix, routePath),
        file: relativeToRoot(absolute),
        description: precedingComment(lines, index),
      });
    });

    if (routes.length) {
      groups.push({ prefix: prefix || "(unmounted)", file: relativeToRoot(absolute), routes });
    }
  }

  const totalRoutes = directRoutes.length + groups.reduce((sum, g) => sum + g.routes.length, 0);
  if (totalRoutes === 0) {
    console.warn(`! No Express routes found in ${relativeToRoot(ROUTES_DIR)}`);
    return null;
  }

  const sections: string[] = [];

  for (const group of groups) {
    sections.push(
      [
        `### \`${group.prefix}\``,
        ``,
        `Defined in \`${group.file}\`.`,
        ``,
        `| Method | Path | Notes |`,
        `| --- | --- | --- |`,
        ...group.routes.map(
          (route) => `| ${route.method} | \`${route.fullPath}\` | ${route.description ?? "—"} |`,
        ),
        ``,
      ].join("\n"),
    );
  }

  if (directRoutes.length) {
    sections.push(
      [
        `### Root-level`,
        ``,
        `Defined in \`${relativeToRoot(API_ENTRY)}\`.`,
        ``,
        `| Method | Path | Notes |`,
        `| --- | --- | --- |`,
        ...directRoutes.map(
          (route) => `| ${route.method} | \`${route.fullPath}\` | ${route.description ?? "—"} |`,
        ),
        ``,
      ].join("\n"),
    );
  }

  return [
    header("API routes", [relativeToRoot(ROUTES_DIR), relativeToRoot(API_ENTRY)]),
    `${totalRoutes} route${totalRoutes === 1 ? "" : "s"}.`,
    ``,
    ...sections,
  ].join("\n");
}

// ------------------------------------------------------------------ main ---

async function main() {
  fs.mkdirSync(OUT_DIR, { recursive: true });

  const outputs: [string, string | null][] = [
    ["schema.md", await generateSchemaDoc()],
    ["routes.md", generateRoutesDoc()],
  ];

  let written = 0;
  for (const [filename, contents] of outputs) {
    if (contents === null) continue;
    const target = path.join(OUT_DIR, filename);
    fs.writeFileSync(target, `${contents.trimEnd()}\n`);
    console.log(`✓ ${relativeToRoot(target)}`);
    written += 1;
  }

  if (written === 0) {
    console.error("Nothing generated — see warnings above.");
    process.exit(1);
  }
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
